force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ReviewNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewBuilder.cls
/**
 * Created by dawid.zamojda on 22.08.2023.
 */

public with sharing class ReviewBuilder {
    private String author;
    private String comment;
    private Date createdAt;
    private Integer rating;
    private String product;
    public ReviewBuilder() {}
    public ReviewBuilder setAuthor(String author) {
        this.author = author;
        return this;
    }
    public ReviewBuilder setRating(Integer rating) {
        this.rating = rating;
        return this;
    }
    public ReviewBuilder setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    public ReviewBuilder setComment(String comment) {
        this.comment = comment;
        return this;
    }
    public ReviewBuilder setProduct(String product) {
        this.product = product;
        return this;
    }
    public Review__c build() {
        Review__c review = new Review__c();
        review.Author__c = author;
        review.Rating__c = rating;
        review.Created_At__c = createdAt;
        review.Comment__c = comment;
        review.Product__c = product;

        return review;
    }
}