force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ReviewNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CommentsController.cls
/**
 * Created by dawid.zamojda on 22.09.2023.
 */

public with sharing class CommentsController {
    @AuraEnabled(Cacheable=true)
    public static Review__c getComment(String user, Id productId){
        Review__c review = [
                SELECT Id, Name, Author__c, Product__c, Comment__c, Rating__c, Approval_Status__c
                FROM Review__c
                WHERE Author__c = :user AND
                    Product__c = :productId AND
                    Approval_Status__c = 'Approved'
                LIMIT 1
        ];
        return review;
    }

    @AuraEnabled
    public static String deleteReview(String recordId, String author){
        Review__c review = [
                SELECT Id, Comment__c, Rating__c, Approval_Status__c
                FROM Review__c
                WHERE Product__c = :recordId
                AND Author__c = :author
                AND Approval_Status__c = 'Approved'
                LIMIT 1
        ];
        delete review;
        return review.Id;
    }
}