force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ReviewNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewBuilderTest.cls
@isTest
public class ReviewBuilderTest {
    @IsTest
    public static void testReviewBuilderBuild() {
        Product2 testProduct = TestDataFactory.CreateProducts(1)[0];
        String testProductId = testProduct.Id;

        Review__c review = new ReviewBuilder()
                .setAuthor('John Doe')
                .setRating(5)
                .setCreatedAt(Date.newInstance(2023, 8, 20))
                .setComment('Excellent product!')
                .setProduct(testProductId)
                .build();

        System.assertEquals('John Doe', review.Author__c);
        System.assertEquals(5, review.Rating__c);
        System.assertEquals(Date.newInstance(2023, 8, 20), review.Created_At__c);
        System.assertEquals('Excellent product!', review.Comment__c);
        System.assertEquals(testProductId, review.Product__c);
    }

    @IsTest
    public static void testReviewBuilderBuildAndSave(){
        Product2 testProduct = TestDataFactory.CreateProducts(1)[0];
        String testProductId = testProduct.Id;

        Review__c review = new ReviewBuilder()
                .setAuthor('John Doe')
                .setRating(5)
                .setCreatedAt(Date.newInstance(2023, 8, 20))
                .setComment('Excellent product!')
                .setProduct(testProductId)
                .buildAndSave();

        System.assertNotEquals(null, review.Id);
    }
}