src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Accommodation__c</fullName>
        <label>Accommodation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Hostel</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
                <value>
                    <fullName>Cottage</fullName>
                </value>
                <value>
                    <fullName>Airbnb</fullName>
                </value>
                <value>
                    <fullName>Campsite</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cities__c</fullName>
        <label>Cities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Members__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Members</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of trips (in days)</description>
        <label>Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_All_Inclusive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is All Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Limit__c</fullName>
        <label>Member Limit</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not provided</fullName>
                    <default>true</default>
                    <label>Not provided</label>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
                <value>
                    <fullName>Airplane</fullName>
                </value>
                <value>
                    <fullName>Bike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductWrapper.cls
/**
 * Created by dawid.zamojda on 11.07.2023.
 */

public with sharing class ProductWrapper {
    public String name {get;set;}
    public String accommodation {get; set;}
    public List<String> cities {get;set;}
    public String continent {get;set;}
    public Integer currentMembers {get;set;}
    public Integer duration {get;set;}
    public Date startDate {get;set;}
    public Date endDate {get;set;}
    public Boolean isAllInclusive {get;set;}
    public Integer memberLimit {get;set;}
    public String productDescription {get;set;}
    public String summary {get;set;}
    public String transportation {get;set;}

    public ProductWrapper(){
        this.name = '';
        this.accommodation = '';
        this.cities = new List<String>();
        this.continent = '';
        this.currentMembers = 0;
        this.duration = 0;
        this.startDate = null;
        this.endDate = null;
        this.isAllInclusive = false;
        this.memberLimit = 0;
        this.productDescription = '';
        this.summary = '';
        this.transportation = '';
    }

    public ProductWrapper(Product2 product){
        this.name = product.Name;
        this.accommodation = product.Accommodation__c;
        this.cities = product.Cities__c.split(',');
        this.continent = product.Continent__c;
        this.currentMembers = (Integer) product.Current_Members__c;
        this.duration = (Integer) product.Duration__c;
        this.startDate = product.Start_Date__c;
        this.endDate = product.End_Date__c;
        this.isAllInclusive = product.Is_All_Inclusive__c;
        this.memberLimit = (Integer) product.Member_Limit__c;
        this.productDescription = product.Description;
        this.summary = product.Summary__c;
        this.transportation = product.Transportation__c;
    }
}