src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Accommodation__c</fullName>
        <label>Accommodation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Hostel</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
                <value>
                    <fullName>Cottage</fullName>
                </value>
                <value>
                    <fullName>Airbnb</fullName>
                </value>
                <value>
                    <fullName>Campsite</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cities__c</fullName>
        <label>Cities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Members__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Members</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of trips (in days)</description>
        <label>Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_All_Inclusive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is All Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not provided</fullName>
                    <default>true</default>
                    <label>Not provided</label>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
                <value>
                    <fullName>Airplane</fullName>
                </value>
                <value>
                    <fullName>Bike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Spots_Left__c.field-meta.xml
<CustomField>
    <fullName>Spots_Left__c</fullName>
    <formula>Member_Limit__c -  Current_Members__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spots Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Trip_Start_End__c.field-meta.xml
<CustomField>
    <fullName>Trip_Start_End__c</fullName>
    <formula>TEXT(Start_Date__c) &amp; &quot; - &quot; &amp;  TEXT(End_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip Start End</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ReviewNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductComparerHandler.cls
/**
 * Created by dawid.zamojda on 22.08.2023.
 */

public with sharing class ProductComparerHandler {
    public static List<Product2> getProductNames() {
        return [
                SELECT Id, Name
                FROM Product2
        ];
    }
    public static Product2 getProductDetails(String productId) {
        return [
                SELECT Id, Name, Summary__c, Accommodation__c, Cities__c, Continent__c, Current_Members__c,
                        Is_All_Inclusive__c, Spots_Left__c, Trip_Start_End__c, Transportation__c, Duration__c
                FROM Product2
                WHERE Id = :productId
        ];
    }
    public static Map<String, Object> getReviewDetails(String productId){
        Map<String, Object> resultMap = new Map<String, Object>();

        List<AggregateResult> results =  [
                SELECT COUNT(Rating__c) Votes, AVG(Rating__c) Average
                FROM Review__c
                WHERE Product__c = :productId
        ];

        if (!(results.size() == 0)) {
            AggregateResult result = results[0];

            Integer votes = (Integer) result.get('Votes');
            Decimal average = (Decimal) result.get('Average');

            resultMap.put('Votes', votes != null ? votes : 0);
            resultMap.put('Average', average != null ? average.setScale(2) : 0.00);
        } else {
            resultMap.put('Votes', 0);
            resultMap.put('Average', 0.00);
        }
        return resultMap;
    }
    public static PricebookEntry getProductPrice(String productId){
        String defaultCurrency = [
                SELECT CurrencyIsoCode
                FROM WebStore
                WHERE Name = 'Oddysey'
                LIMIT 1
        ].CurrencyIsoCode;

        return [
                SELECT UnitPrice
                FROM PricebookEntry
                WHERE Product2Id = :productId AND
                CurrencyIsoCode = :defaultCurrency AND
                Pricebook2Id IN  (SELECT Id
                                FROM Pricebook2
                                WHERE Name LIKE '%Odyssey%')
        ];
    }
}