src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Accommodation__c</fullName>
        <label>Accommodation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Hostel</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
                <value>
                    <fullName>Cottage</fullName>
                </value>
                <value>
                    <fullName>Airbnb</fullName>
                </value>
                <value>
                    <fullName>Campsite</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cities__c</fullName>
        <label>Cities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Members__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Members</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of trips (in days)</description>
        <label>Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_All_Inclusive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is All Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Limit__c</fullName>
        <label>Member Limit</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not provided</fullName>
                    <default>true</default>
                    <label>Not provided</label>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
                <value>
                    <fullName>Airplane</fullName>
                </value>
                <value>
                    <fullName>Bike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductManagementController.cls
public with sharing class ProductManagementController {
    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts() {
        return [SELECT
                Id,
                Name,
                Cities__c,
                Accommodation__c,
                Duration__c,
                Start_Date__c,
                End_Date__c,
                Continent__c,
                Is_All_Inclusive__c,
                Transportation__c,
                Member_Limit__c,
                Current_Members__c,
                Summary__c,
                Description
        FROM Product2];
    }

    @AuraEnabled
    public static List<Product2> saveProduct(Product2 product) {
        if (product.Id != null) {
            update product;
        } else {
            insert product;
        }
        return getProducts();
    }

    @AuraEnabled
    public static Id deleteProductRecord(Id productId) {
        Id result = null;
        try {
            delete new Product2(Id = productId);
            result = productId;
        } catch (DmlException e) {
            result = null;
            throw new AuraHandledException('Error occured while deleting the record');

        }
        return result;
    }
}