src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Accommodation__c</fullName>
        <label>Accommodation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Hostel</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
                <value>
                    <fullName>Cottage</fullName>
                </value>
                <value>
                    <fullName>Airbnb</fullName>
                </value>
                <value>
                    <fullName>Campsite</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cities__c</fullName>
        <label>Cities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Members__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Members</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of trips (in days)</description>
        <label>Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_All_Inclusive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is All Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Limit__c</fullName>
        <label>Member Limit</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not provided</fullName>
                    <default>true</default>
                    <label>Not provided</label>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
                <value>
                    <fullName>Airplane</fullName>
                </value>
                <value>
                    <fullName>Bike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductBuilder.cls
/**
 * Created by dawid.zamojda on 22.08.2023.
 */

public with sharing class ProductBuilder {
    private String accommodation;
    private String cities;
    private String continent;
    private Integer currentMembers;
    private Date startDate;
    private Date endDate;
    private Boolean isAllInclusive;
    private Integer memberLimit;
    private String transportation;
    private String name;
    private String summary;
    private Integer duration;

    public ProductBuilder() {
        this.accommodation = 'Hotel';
        this.cities = 'Bialystok,Warszawa';
        this.continent = 'Europe';
        this.currentMembers = 0;
        this.startDate = Date.newInstance(2023, 8, 1);
        this.endDate = Date.newInstance(2023, 8, 5);
        this.isAllInclusive = false;
        this.memberLimit = 10;
        this.transportation = 'Bus';
        this.name = 'Test trip';
        this.summary = 'Test summary';
        this.duration = 4;
    }

    public ProductBuilder setDuration(Integer duration){
        this.duration = duration;
        return this;
    }
    public ProductBuilder setTransportation(String transportation) {
        this.transportation = transportation;
        return this;
    }
    public ProductBuilder setMemberLimit(Integer memberLimit) {
        this.memberLimit = memberLimit;
        return this;
    }
    public ProductBuilder setIsAllInclusive(Boolean isAllInclusive) {
        this.isAllInclusive = isAllInclusive;
        return this;
    }
    public ProductBuilder setEndDate(Date endDate) {
        this.endDate = endDate;
        return this;
    }
    public ProductBuilder setStartDate(Date startDate) {
        this.startDate = startDate;
        return this;
    }
    public ProductBuilder setAccommodation(String accommodation) {
        this.accommodation = accommodation;
        return this;
    }
    public ProductBuilder setCities(String cities) {
        this.cities = cities;
        return this;
    }
    public ProductBuilder setContinent(String continent) {
        this.continent = continent;
        return this;
    }
    public ProductBuilder setCurrentMembers(Integer currentMembers) {
        this.currentMembers = currentMembers;
        return this;
    }
    public ProductBuilder setName(String name) {
        this.name = name;
        return this;
    }
    public ProductBuilder setSummary(String summary) {
        this.summary = summary;
        return this;
    }
    public Product2 build() {
        return new Product2(
                Name = this.name,
                Accommodation__c = this.accommodation,
                Cities__c = this.cities,
                Continent__c = this.continent,
                Current_Members__c = this.currentMembers,
                Start_Date__c = this.startDate,
                End_Date__c = this.endDate,
                Is_All_Inclusive__c = this.isAllInclusive,
                Member_Limit__c = this.memberLimit,
                Transportation__c = this.transportation,
                Summary__c = this.summary,
                Duration__c = this.duration
        );
    }
}