src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Accommodation__c</fullName>
        <label>Accommodation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Hostel</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
                <value>
                    <fullName>Cottage</fullName>
                </value>
                <value>
                    <fullName>Airbnb</fullName>
                </value>
                <value>
                    <fullName>Campsite</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cities__c</fullName>
        <label>Cities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Members__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Members</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_All_Inclusive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is All Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Limit__c</fullName>
        <label>Member Limit</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not provided</fullName>
                    <default>true</default>
                    <label>Not provided</label>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
                <value>
                    <fullName>Airplane</fullName>
                </value>
                <value>
                    <fullName>Bike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductBuilderTest.cls
/**
 * Created by dawid.zamojda on 22.08.2023.
 */

@isTest
public class ProductBuilderTest {
    @isTest
    public static void testProductBuilder() {
        String testName = 'Test Product';
        String testSummary = 'Test summary';
        String testAccommodation = 'Hotel';
        String testCities = 'City1, City2';
        String testContinent = 'North America';
        Integer testCurrentMembers = 50;
        Date testStartDate = Date.newInstance(2023, 8, 1);
        Date testEndDate = Date.newInstance(2023, 8, 15);
        Boolean testIsAllInclusive = true;
        Integer testMemberLimit = 100;
        String testTransportation = 'Flight';

        Product2 product = new ProductBuilder()
                .setName(testName)
                .setSummary(testSummary)
                .setAccommodation(testAccommodation)
                .setCities(testCities)
                .setContinent(testContinent)
                .setCurrentMembers(testCurrentMembers)
                .setStartDate(testStartDate)
                .setEndDate(testEndDate)
                .setIsAllInclusive(testIsAllInclusive)
                .setMemberLimit(testMemberLimit)
                .setTransportation(testTransportation)
                .build();

        System.assertEquals(testName, product.Name);
        System.assertEquals(testSummary, product.Summary__c);
        System.assertEquals(testAccommodation, product.Accommodation__c);
        System.assertEquals(testCities, product.Cities__c);
        System.assertEquals(testContinent, product.Continent__c);
        System.assertEquals(testCurrentMembers, product.Current_Members__c);
        System.assertEquals(testStartDate, product.Start_Date__c);
        System.assertEquals(testEndDate, product.End_Date__c);
        System.assertEquals(testIsAllInclusive, product.Is_All_Inclusive__c);
        System.assertEquals(testMemberLimit, product.Member_Limit__c);
        System.assertEquals(testTransportation, product.Transportation__c);
    }
}