src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Member_Limit__c</fullName>
        <label>Member Limit</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ReviewNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductComparerControllerTest.cls
@isTest
private class ProductComparerControllerTest {

    @isTest
    static void testGetProductNames() {
        List<Product2> products = new List<Product2>{
                new Product2(Name = 'Product 1', Member_Limit__c = 10),
                new Product2(Name = 'Product 2', Member_Limit__c = 10)
        };
        insert products;

        Test.startTest();
        List<Product2> results = productComparerController.getProductNames();
        Test.stopTest();

        System.assertEquals(products.size(), results.size());
    }

    @isTest
    static void testGetProductDetails() {
        Product2 testProduct = new Product2(
                Name = 'Test Product',
                Summary__c = 'Product summary',
                Member_Limit__c =10
                );
        insert testProduct;

        Test.startTest();
        Product2 result = productComparerController.getProductDetails(testProduct.Id);
        Test.stopTest();

        System.assertEquals(testProduct.Name, result.Name);
        System.assertEquals(testProduct.Summary__c, result.Summary__c);
    }

    @isTest
    static void testGetReviewDetails() {
        Product2 testProduct = new Product2(Name = 'Test Product', Member_Limit__c=10);
        insert testProduct;

        Review__c testReview = new Review__c(Product__c = testProduct.Id, Rating__c = 4, Author__c = 'Dawid Żamojda');
        insert testReview;

        Test.startTest();
        Map<String, Object> resultMap = productComparerController.getReviewDetails(testProduct.Id);
        Test.stopTest();

        System.assertEquals(1, resultMap.get('Votes'));
        System.assertEquals(4.00, resultMap.get('Average'));
    }
}